name = "petshop-web"

[application]
main = "com.example.petshop.PetshopApplication"

[spring-boot]
version = "latest"

[dependencies]
petshop-service = { workspace = true }
starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }

[test-dependencies]
starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
