name    = "nia-core-designsystem"
group   = "com.google.samples.apps.nowinandroid"
version = "0.1.0"
java    = 21
kotlin  = "^2.4.0"

[android]
namespace   = "com.google.samples.apps.nowinandroid.core.designsystem"
compile-sdk = 36
min-sdk     = 23
library     = true
compose     = true

[platform-dependencies]
compose = { group = "androidx.compose", name = "compose-bom-alpha", version = "=2026.07.01" }

[dependencies]
compose-foundation        = { group = "androidx.compose.foundation", name = "foundation" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
compose-icons-extended    = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3         = { group = "androidx.compose.material3", name = "material3" }
material3-adaptive        = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
material3-nav-suite       = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
compose-runtime           = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui-util           = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coil-compose              = { group = "io.coil-kt", name = "coil-compose", version = "=2.7.0" }

[test-dependencies]
junit-platform-launcher = "=6.1.1"

[repositories]
central = "https://repo.maven.apache.org/maven2/"
google  = "https://dl.google.com/dl/android/maven2/"
