name    = "nia-core-designsystem"
group   = "com.google.samples.apps.nowinandroid"
version = "0.1.0"
java    = 21
kotlin  = "^2.4.0"

[android]
namespace   = "com.google.samples.apps.nowinandroid.core.designsystem"
compile-sdk = 36
min-sdk     = 23
library     = true
compose     = true

[platform-dependencies]
compose = "androidx.compose:compose-bom-alpha:=2026.07.01"

[dependencies]
compose-foundation        = "androidx.compose.foundation:foundation"
compose-foundation-layout = "androidx.compose.foundation:foundation-layout"
compose-icons-extended    = "androidx.compose.material:material-icons-extended"
compose-material3         = "androidx.compose.material3:material3"
material3-adaptive        = "androidx.compose.material3.adaptive:adaptive"
material3-nav-suite       = "androidx.compose.material3:material3-adaptive-navigation-suite"
compose-runtime           = "androidx.compose.runtime:runtime"
compose-ui-util           = "androidx.compose.ui:ui-util"
compose-ui-tooling-preview = "androidx.compose.ui:ui-tooling-preview"
coil-compose              = "=2.7.0"

[test-dependencies]
junit-platform-launcher = "=6.1.1"

[repositories]
central = "https://repo.maven.apache.org/maven2/"
google  = "https://dl.google.com/dl/android/maven2/"
