[project]
name    = "nia-core-model"
group   = "com.google.samples.apps.nowinandroid"
version = "0.1.0"
java    = 21
kotlin  = "^2.4.0"

[dependencies]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "=0.6.1" }

[test-dependencies]
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "=6.1.1" }

[repositories]
central = "https://repo.maven.apache.org/maven2/"
google  = "https://dl.google.com/dl/android/maven2/"
